model: yolov5s-cls.pt
data: ../../data/mri_dataset
epochs: 50
batch_size: 32
imgsz: 224
nosave: false
cache: null
device: ''
workers: 8
project: ../../runs/classify
name: mri_classifier
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 0
local_rank: -1
save_dir: ..\..\runs\classify\mri_classifier
